### PR TITLE
fix(date-picker-month): invoke selectDate action with onclick

### PR DESCRIPTION
**Pull request by omairvaiyani**
In the context of wormholes, setting an action in this manner: ```<button {{action actionName}}```, will result in the action being ignored by the local context. Or at least, that the issue that I found, when using ```renderInPlace: false``` and a blocked-component. This PR resolved my issue.

### CODE REVIEW

**Comment by mydea** [comment]
Hmm, I think that must be something about your setup then - as this should (and does, as far as I see?) definitely work! 

What exactly is your problem? In our applications, we do have wormholes (e.g. `{{-in-element}}`) where we render a date picker into, and it all works fine.

**Comment by omairvaiyani** [comment]
Perhaps it is my specific setup, though I have not done anything obviously different.

Take a look at this [issue](https://github.com/cibernox/ember-basic-dropdown/issues/419)

**Comment by mydea** [comment]
Ah, so you are not rendering the ember app into the document.body?

In this case, I would propose you simply add the necessary wormhole for ember-basic-dropdown manually inside of your ember app DOM element: `<div id="ember-basic-dropdown-wormhole"></div>`. Then it should render it in there, and the event handlers should work correctly.

**Comment by omairvaiyani** [comment]
So as far as I can tell, my app is rendered into the document.body, where else could I have rendered it? Is there a downside to this PR that may negatively affect others?

**Comment by mydea** [comment]
It's probably not a huge deal, but it will attach a DOM listener to each element vs. just use the regular event dispatch system of Ember. 

More importantly, I'd like to understand what the problem is first. The issue you linked to in ember-basic-dropdown seems to be related, but in there he writes that the wormhole is outside of the basic app container.

Can you show your `config/environment.js` and `index.html` files? Maybe that helps to clear up what's going on there.

**Pull request closed without merging**
